uploads = []
outputs = []

[[generated]]
id = "oay6Wy5eGhboe9ztO78WA"
uri = "file://artifacts/hatchup/src/assets/images/lava-dragon.png"
type = "image"
title = "Lava dragon creature"

[[generated]]
id = "Gc9U5Ldfg-lFQvBOcEYTh"
uri = "file://artifacts/hatchup/src/assets/images/crystal-guardian.png"
type = "image"
title = "Crystal guardian creature"

[[generated]]
id = "MNq6XTWLdZwcq0XK8YnkK"
uri = "file://artifacts/hatchup/src/assets/images/cosmic-entity.png"
type = "image"
title = "Cosmic entity creature"

[[generated]]
id = "f_wACn4loR1kfnb7Wu7m2"
uri = "file://artifacts/hatchup/src/assets/images/shadow-beast.png"
type = "image"
title = "Shadow beast creature"

[[generated]]
id = "lmammI7tTp9pHxS9dz0UX"
uri = "file://artifacts/hatchup/src/assets/images/candy-monster.png"
type = "image"
title = "Candy monster creature"

[[generated]]
id = "PBbrSIRt1e5fLg-prDsN9"
uri = "file://artifacts/hatchup/src/assets/images/cyber-creature.png"
type = "image"
title = "Cyber creature"

[[generated]]
id = "M0S7U81QzifCEGYDBOH4-"
uri = "file://artifacts/hatchup/public/opengraph.png"
type = "image"
title = "hatchup opengraph share card"

[[generated]]
id = "SOXvENsbHAtpQNcQU-TpO"
uri = "file://artifacts/hatchup-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uGB0h4glKhFn8oNB69aC5"
uri = "file://artifacts/hatchup-mobile/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
