import { Router, type IRouter } from "express";
import healthRouter from "./health.ts";
import playersRouter from "./players.ts";
import hatchlingsRouter from "./hatchlings.ts";
import evolutionsRouter from "./evolutions.ts";
import competitionsRouter from "./competitions.ts";
import leaderboardsRouter from "./leaderboards.ts";
import itemsRouter from "./items.ts";
import eventsRouter from "./events.ts";
import clubsRouter from "./clubs.ts";
import eggsRouter from "./eggs.ts";
import fitnessRouter from "./fitness.ts";
import trainingRouter from "./training.ts";
import healthSyncRouter from "./health-sync.ts";
import groupsRouter from "./groups.ts";
import badgesRouter from "./badges.ts";
import rewardsRouter from "./rewards.ts";
import safetyRouter from "./safety.ts";
import coachRouter from "./coach.ts";
import recordsRouter from "./records.ts";
import nutritionRouter from "./nutrition.ts";
import battlesRouter from "./battles.ts";
import artifactsRouter from "./artifacts.ts";
import challengesRouter from "./challenges.ts";
import socialRouter from "./social.ts";
import accessibilityRouter from "./accessibility.ts";
import locationsRouter from "./locations.ts";
import subscriptionRouter from "./subscription.ts";
import shieldsRouter from "./shields.ts";
import storageRouter from "./storage.ts";
import notificationsRouter from "./notifications.ts";
import pushRouter from "./push.ts";
import adminRouter from "./admin.ts";
import analyticsRouter from "./analytics.ts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(playersRouter);
router.use(hatchlingsRouter);
router.use(evolutionsRouter);
router.use(competitionsRouter);
router.use(leaderboardsRouter);
router.use(itemsRouter);
router.use(eventsRouter);
router.use(clubsRouter);
router.use(eggsRouter);
router.use(fitnessRouter);
router.use(trainingRouter);
router.use(healthSyncRouter);
router.use(groupsRouter);
router.use(badgesRouter);
router.use(rewardsRouter);
router.use(safetyRouter);
router.use(coachRouter);
router.use(recordsRouter);
router.use(nutritionRouter);
router.use(battlesRouter);
router.use(artifactsRouter);
router.use(challengesRouter);
router.use(socialRouter);
router.use(accessibilityRouter);
router.use(locationsRouter);
router.use(subscriptionRouter);
router.use(shieldsRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(pushRouter);
router.use(adminRouter);
router.use(analyticsRouter);

export default router;
