import { Router, type IRouter } from "express";
import healthRouter from "./health";
import playersRouter from "./players";
import hatchlingsRouter from "./hatchlings";
import evolutionsRouter from "./evolutions";
import competitionsRouter from "./competitions";
import leaderboardsRouter from "./leaderboards";
import itemsRouter from "./items";
import eventsRouter from "./events";
import clubsRouter from "./clubs";
import eggsRouter from "./eggs";
import fitnessRouter from "./fitness";
import trainingRouter from "./training";
import healthSyncRouter from "./health-sync";
import groupsRouter from "./groups";
import badgesRouter from "./badges";
import rewardsRouter from "./rewards";
import safetyRouter from "./safety";

const router: IRouter = Router();

router.use(healthRouter);
router.use(playersRouter);
router.use(hatchlingsRouter);
router.use(evolutionsRouter);
router.use(competitionsRouter);
router.use(leaderboardsRouter);
router.use(itemsRouter);
router.use(eventsRouter);
router.use(clubsRouter);
router.use(eggsRouter);
router.use(fitnessRouter);
router.use(trainingRouter);
router.use(healthSyncRouter);
router.use(groupsRouter);
router.use(badgesRouter);
router.use(rewardsRouter);
router.use(safetyRouter);

export default router;
